---
title: "risk pre"
output: html_document
---
initiate the condition of three countries and their risk transporting mechnism
```{r setup, include=FALSE}
pollutiontrans=matrix(data=c(1,1.5,2,0,1,1.5,0,0,1),nrow=3)
financialtrans=matrix(c(1,0.9,0.8,0.9,1,0.9,0.8,0.9,1),nrow=3)
S0=matrix(c(3000,500,1000,2000,2500,3000),nrow=2)
rownames(S0)=c("evironment resurces","financial resources")
colnames(S0)=c("A","B","C")
investing_pollution=matrix(c(300,0,0,0,100,0,0,0,30),nrow = 3)
colnames(investing_pollution)=c("A","B","C")
technology_up=c(0.1,0.4,0.8)
waste_down=0.2
market=t(c(400,800,1200))
techs=diag(1,nrow = 3)
colnames(techs)=c("A","B","C")
earning=market%*% sweep(techs,1,apply(techs, 1, sum),'/')
envraising=0.3
H=list(S0)
counter=matrix(0,nrow = 2,ncol = 3)
rownames(counter)=c("evironment disaster","financial crisis")
colnames(counter)=c("A","B","C")
```
initiate choices:
```{r}
trying=function(x){
  n=nrow(x)
  m=ncol(x)
  lucky=matrix(runif(n*m),nrow = n)
  return(ifelse(lucky-x>0,0,1))
}
disaster=function(states){
  penv=250/states[1,]
  pfin=250/states[2,]
  answer=-0.15*trying(rbind(penv,pfin))
  return(states*answer)
}
#return the profits and pollution
invest_industry=function(actor){
  profits=earning%*%actor
  pollutes=-colSums(investing_pollution%*%actor)
  return(rbind(pollutes,profits))
}
#return the cost of invest existed tech
invest_technology=function(actor){
  new_pollution=investing_pollution-waste_down*actor%*%investing_pollution
  investing_pollution<<-new_pollution
  return(t(matrix(c(0,0,0,-100,-100,-100),nrow = 3)))
}
#return the cost of invest new tech
invest_newtech=function(actor){
  target=actor%*%technology_up
  result=trying(target)
  newtechs=techs
  for (x in 1:ncol(actor)) {
    if(result[x,1]>0){
      if(identical(newtechs[,x],c(1,0,0))) newtechs[,x]=c(1,1,0)
      else if(identical(newtechs[,x],c(1,1,0))) newtechs[,x]=c(1,1,1)
      else if(identical(newtechs[,x],c(0,1,0))) newtechs[,x]=c(0,1,1)
      else if(identical(newtechs[,x],c(0,1,1))) newtechs[,x]=c(1,1,1)
      else if(identical(newtechs[,x],c(0,0,1))) newtechs[,x]=c(0,1,1)
    }
  }
  earning<<-market%*% sweep(newtechs,1,apply(newtechs, 1, sum),'/')
  techs<<-newtechs
  investing_pollution<<-investing_pollution%*%techs
  return(t(matrix(c(0,0,0,-150,-150,-150),nrow = 3)))
}
#return the cost and environment imporve
envimporve=function(actor,x) {
  profits=c(-150,-150,-150)%*%actor
  pollutes=envraising*x[1,]%*%actor
  return(rbind(pollutes,profits))
}


#Action and display function function: 0 for in action, 1 for investing industry, 2 for investing existed technology, 3 for investing new technology, 4 for investing environment. 

Actions=function(choosing){
  case=as.matrix(tail(H,1)[[1]])
  result=disaster(case)
  for (i in 1:3) {
    if(result[1,i]<0){
      print(paste(colnames(S0)[i]," faces a natural disaster."))
      counter[1,i]<<-counter[1,i]+1
    }
    if(result[2,i]<0){
      print(paste(colnames(S0)[i]," faces a finantical crisis."))
      counter[2,i]<<-counter[2,i]+1
    }
  }
  result=rbind(t(pollutiontrans%*%result[1,]),t(financialtrans%*%result[2,]))
  actions=array(data=0,dim = c(3,3,4))
  for (i in 1:3){
    actions[i,i,choosing[i]]=1
  }
  if(max(actions[,,1])>0){
    tempresult=invest_industry(actions[,,1])
    result=result+rbind(t(pollutiontrans%*%tempresult[1,]),tempresult[2,])
  }
  if(max(actions[,,2]>0)){
    result=result+invest_technology(actions[,,2])
  }
  if(max(actions[,,3]>0)){
    result=result+invest_newtech(actions[,,3])
  }
  if(max(actions[,,4]>0)){
    result=result+envimporve(actions[,,4],case)
  }
  now=case+result
  for (i in 1:3) {
    if(now[1,i]<0){
      print(paste(colnames(S0)[i]," faces a big climate problem that lead the failing of government and refugee for other countries"))
    }
    if(now[2,i]<0){
      print(paste(colnames(S0)[i]," faces a big financial problem that lead the failing of government and makes the market shrinks"))
    }
  }
    H<<-c(H,list(now))
  
}

midtermreport=function(){
  envresult=data.frame(t(sapply(H, function(x) return(x[1,]))))
  colnames(envresult)=c("a","b","c")
  finresult=data.frame(t(sapply(H, function(x) return(x[2,]))))
  colnames(finresult)= c("a","b","c")
  plot(envresult$a,type='b',col="firebrick1",xlab = "round",ylab = "env index",ylim = c(0,max(envresult)),main = "change of envrionment index")
  lines(envresult$b,type='b',col="seagreen")
  lines(envresult$c,type='b',col="cadetblue3")
  plot(finresult$a,l=,type='b',col="firebrick1",xlab = "round",ylab = "fin index",ylim=c(0,max(finresult)),main = "change of finantial index")
  lines(finresult$b,type='b',col="seagreen")
  lines(finresult$c,type='b',col="cadetblue1")
  print(tail(H,1)[[1]])
}

finalreport=function(){
  midtermreport()
  print("technology development:")
  print(techs)
  print("pollution")
  print(investing_pollution)
  print("disaster counting")
  print(counter)
}
```

example
```{r}
Actions(c(0,0,0))
Actions(c(0,0,0))
Actions(c(0,0,0))
Actions(c(0,0,0))
Actions(c(0,0,0))
midtermreport()
```
```{r}
finalreport()
```


round 1

```{r}
Actions(c(1,4,0))
midtermreport()
```
```{r}
Actions(c(4,4,0))
midtermreport()
```
```{r}
Actions(c(2,4,4))
midtermreport()
```
```{r}
Actions(c(0,0,0))
midtermreport()
```
```{r}
Actions(c(0,0,0))
midtermreport()
```
```{r}
Actions(c(0,0,0))
midtermreport()
```
```{r}
finalreport()
```


round 2:


```{r}
finantial_supporting=function(from,to,money){
  n=length(from)
  current=tail(H,1)[[1]]
  for (i in 1:n) {
    if(current[2,from[i]]>money[i]){
    current[2,from[i]]=current[2,from[i]]-money[i]
    current[2,to[i]]=current[2,to[i]]+money[i]
  }}
  H<<-c(H,list(current))
}
```
```{r}
Actions(c(0,0,0))
finantial_supporting(c(0,0),c(0,0),c(0,0))
midtermreport()
```
```{r}
Actions(c(0,0,0))
finantial_supporting(c(0,0),c(0,0),c(0,0))
midtermreport()
```
```{r}
Actions(c(0,0,0))
finantial_supporting(c(0,0),c(0,0),c(0,0))
midtermreport()
```
```{r}
Actions(c(0,0,0))
finantial_supporting(c(0,0),c(0,0),c(0,0))
midtermreport()
```
```{r}
Actions(c(0,0,0))
finantial_supporting(c(0,0),c(0,0),c(0,0))
midtermreport()
```
```{r}
finalreport()
```


